### ISSUE TITLE
Read input csv files automatically.

### ISSUE THREAD

**Issue by mofhu** [Frank-the-Obscure/mascot-csv-process#1]
Read all input csv files in an folder automatically.

**Comment by DeepzSandra** [comment]
how to csv file read and automatically save in mongoose database

**Comment by mofhu** [comment]
@DeepzSandra I'm sorry, but this repo only focus on data process from [Mascot](www.matrixscience.com). Do you really mean this thing?

**Comment by mofhu** [comment]
Read and combine csv files in the folder automatically, commit 6a0c0173bbdf54e83621b6191109fb1c2b044485
using `extract-input-folder.py` to work

**Comment by DeepzSandra** [comment]
Thank you Frank Finished my work!!!! once again thanks u so much!!!
